### ISSUE TITLE
.parse not working as expected (unit tests fail)

### ISSUE THREAD

**Issue by ahx** [Documented-Style-Sheets/Parser#67]
The unit tests added in https://github.com/DSSWG/DSS/pull/66 are failing.

**Comment by ahx** [comment]
Me and @mbrendler just figured out that the bug was introduced in https://github.com/DSSWG/DSS/commit/c0e27bf7a130b61bb10ea4364ad0c373d6bd5b3b, we are taking a deeper look at this right now. Ping here, if you have any thoughts.

**Comment by ahx** [comment]
Work in progress: https://github.com/ahx/DSS/tree/67-fix-parse

**Comment by ahx** [comment]
#69  fixes this for multiline comments that looks like:
```css
/*
* @name Foo
*/
```
…but it still fails for a syntax like mentioned in the README:
```css
//
// @name Foo
//
```

**Comment by ahx** [comment]
Do you have plans how to solve this?

**Comment by darcyclarke** [comment]
@ahx Yep. I had a fix in the works about 2 weeks ago. I'll try and push that up this weekend. Definitely ping me again if you don't see any activity by Monday morning

**Comment by ahx** [comment]
Ping @darcyclarke :heart:  :tulip: :fireworks: :tokyo_tower:

**Comment by yguezeldal** [comment]
ping @darcyclarke :smiley:

**Comment by ahx** [comment]
This project has become pretty stale. – Do you think #68 should be done before trying to solve this within the current implementation?
